### ISSUE TITLE
Read does not accept default data

### ISSUE THREAD

**Issue by mm-gmbd** [blindman2k/SPIFlashSafeFile#1]
The docs state:

> The read function returns the last object written to the flash. If nothing can be read from the flash storage then the provided default value (or null) is returned.

However, looking at the source, function `read` does not accept any arguments at all.

**Comment by blindman2k** [comment]
Resolved in commit [75730e0cb625508c1b7e0c74888b45310815199b](https://github.com/blindman2k/SPIFlashSafeFile/commit/75730e0cb625508c1b7e0c74888b45310815199b)
