### ISSUE TITLE
Error in read: scan.highestId == SPIFLASHSAFEFILE_ID_INVALID

### ISSUE THREAD

**Issue by mm-gmbd** [blindman2k/SPIFlashSafeFile#4]
I cannot seem to open a PR on this repo directly - Github (or me) being dumb, I think.

Anyway, here's the discussion I was hoping to have:
- When I clear the device SPIFlash, set up a SPIFlashSafeFile (using the default arguemnts for number of spaces and copies), and attempt to read, the read returns `false`
- I tracked this down to the following line of code: https://github.com/blindman2k/SPIFlashSafeFile/blob/master/SPIFlashSafeFile.class.nut#L171
- On my local version, I've changed it to log a warning and return the default argument (which I also added in my local version as mentioned in #1 )
- However, this feels like the wrong behavior considering the "SPIFLASHSAFEFILE_ID" is marked as invalid, but I'm not sure if maybe this is just the result of performing a "_scan" on empty SPIFlash...

**Comment by mm-gmbd** [comment]
Actually, I think this is definitely because the SPIFlash was just cleared before the attempt to read, considering the value of "SPIFLASHSAFEFILE_ID_INVALID" is defined [here](https://github.com/blindman2k/SPIFlashSafeFile/blob/master/SPIFlashSafeFile.class.nut#L10) as:

```
const SPIFLASHSAFEFILE_ID_INVALID = -1; // 0xFFFFFFFF
```

And `0xFFFFFFFF` I believe is empty SPIFlash... Maybe using the name SPIFLASHSAFEFILE_ID_EMPTY would be better over SPIFLASHSAFEFILE_ID_INVALID :)

**Comment by blindman2k** [comment]
This behaviour is correct. If there is no data in the file it should return the default value. Invalid and empty are the same thing in this context.
